# Generated by Django 5.2.7 on 2025-11-11 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="School",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("school_id", models.CharField(max_length=20, unique=True)),
                ("school_name", models.CharField(max_length=100)),
                ("address", models.CharField(blank=True, max_length=200)),
                ("school_password", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Class",
            fields=[
                (
                    "class_id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="クラスID"
                    ),
                ),
                (
                    "class_name",
                    models.CharField(max_length=50, verbose_name="クラス名"),
                ),
                ("grade", models.IntegerField(verbose_name="学年")),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.school",
                        verbose_name="学校",
                    ),
                ),
            ],
            options={
                "verbose_name": "クラス",
                "verbose_name_plural": "クラス一覧",
                "db_table": "class",
            },
        ),
        migrations.CreateModel(
            name="AdministratorUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.IntegerField()),
                ("user_password", models.CharField(max_length=20)),
                ("user_position", models.IntegerField()),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.school"
                    ),
                ),
            ],
            options={
                "unique_together": {("user_id", "school")},
            },
        ),
        migrations.CreateModel(
            name="TeacherUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.IntegerField()),
                ("user_name", models.CharField(max_length=50)),
                ("user_spell", models.CharField(default="", max_length=50)),
                (
                    "gendar",
                    models.IntegerField(
                        choices=[(0, "男性"), (1, "女性"), (2, "その他")], default=0
                    ),
                ),
                ("birthdate", models.DateField()),
                ("user_password", models.CharField(max_length=20)),
                ("user_position", models.IntegerField()),
                (
                    "classes",
                    models.ManyToManyField(
                        blank=True, related_name="teachers", to="core.class"
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.school"
                    ),
                ),
            ],
            options={
                "abstract": False,
                "unique_together": {("user_id", "school")},
            },
        ),
    ]
