# Generated by Django 5.2.7 on 2025-10-29 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="School",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("school_id", models.CharField(max_length=20, unique=True)),
                ("school_name", models.CharField(max_length=100)),
                ("address", models.CharField(blank=True, max_length=200)),
                ("school_password", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.IntegerField()),
                ("user_name", models.CharField(max_length=50)),
                ("user_spell", models.CharField(default="", max_length=50)),
                ("gendar", models.IntegerField(default=0)),
                ("birthdate", models.DateField()),
                ("user_password", models.CharField(max_length=20)),
                ("user_position", models.IntegerField(default=0)),
                ("class_id", models.IntegerField(null=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.school"
                    ),
                ),
            ],
            options={
                "unique_together": {("user_id", "school")},
            },
        ),
    ]
