# Generated by Django 5.2.7 on 2025-10-30 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="gendar",
            field=models.IntegerField(
                choices=[(0, "男性"), (1, "女性"), (2, "その他")], default=0
            ),
        ),
    ]
