# Generated by Django 5.2.7 on 2025-11-05 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_user_gendar"),
    ]

    operations = [
        migrations.CreateModel(
            name="Class",
            fields=[
                (
                    "class_id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="クラスID"
                    ),
                ),
                ("school_id", models.IntegerField(verbose_name="学校ID")),
                (
                    "class_name",
                    models.CharField(max_length=50, verbose_name="クラス名"),
                ),
                ("grade", models.IntegerField(verbose_name="学年")),
                (
                    "homeroom_teacher_id",
                    models.IntegerField(verbose_name="担任ユーザーID"),
                ),
            ],
            options={
                "verbose_name": "クラス",
                "verbose_name_plural": "クラス一覧",
                "db_table": "class",
            },
        ),
    ]
