# Generated by Django 5.2.7 on 2025-11-06 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_class"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="User",
            new_name="AdministratorUser",
        ),
        migrations.RemoveField(
            model_name="class",
            name="homeroom_teacher_id",
        ),
    ]
