# Generated by Django 5.2.7 on 2025-11-20 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_studentuser"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="studentuser",
            options={},
        ),
        migrations.AlterUniqueTogether(
            name="studentuser",
            unique_together={("user_id", "school")},
        ),
    ]
