# Generated by Django 5.2.7 on 2025-11-06 02:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_rename_user_administratoruser_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeacherUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.IntegerField()),
                ("user_name", models.CharField(max_length=50)),
                ("user_spell", models.CharField(default="", max_length=50)),
                (
                    "gendar",
                    models.IntegerField(
                        choices=[(0, "男性"), (1, "女性"), (2, "その他")], default=0
                    ),
                ),
                ("birthdate", models.DateField()),
                ("user_password", models.CharField(max_length=20)),
                ("user_position", models.IntegerField(default=1)),
                ("class_id", models.IntegerField(blank=True, null=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.school"
                    ),
                ),
            ],
            options={
                "unique_together": {("user_id", "school")},
            },
        ),
    ]
