# Generated by Django 5.2.7 on 2025-11-06 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_teacheruser"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teacheruser",
            name="class_id",
        ),
        migrations.AddField(
            model_name="teacheruser",
            name="classes",
            field=models.ManyToManyField(
                blank=True, related_name="teachers", to="core.class"
            ),
        ),
    ]
