# Generated by Django 5.2.7 on 2025-11-07 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_remove_teacheruser_class_id_teacheruser_classes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="administratoruser",
            name="user_position",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="teacheruser",
            name="user_position",
            field=models.IntegerField(),
        ),
    ]
