# Generated by Django 5.2.7 on 2025-11-13 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="teacheruser",
            old_name="gendar",
            new_name="gender",
        ),
    ]
