# Generated by Django 5.2.7 on 2025-11-13 02:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_rename_gendar_teacheruser_gender"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.IntegerField()),
                ("user_name", models.CharField(max_length=50)),
                ("user_spell", models.CharField(default="", max_length=50)),
                (
                    "gender",
                    models.IntegerField(
                        choices=[(0, "男性"), (1, "女性"), (2, "その他")], default=0
                    ),
                ),
                ("birthdate", models.DateField()),
                ("user_password", models.CharField(max_length=20)),
                ("user_position", models.IntegerField()),
                (
                    "classes",
                    models.ManyToManyField(
                        blank=True, related_name="students", to="core.class"
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.school"
                    ),
                ),
            ],
            options={
                "verbose_name": "生徒",
                "verbose_name_plural": "生徒",
            },
        ),
    ]
