# Generated by Django 4.2.27 on 2026-06-12 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_school_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatReadState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('room_name', models.CharField(max_length=100)),
                ('last_read_at', models.DateTimeField(blank=True, null=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.school')),
            ],
            options={
                'indexes': [models.Index(fields=['school', 'user_id', 'room_name'], name='core_chatre_school__849e8d_idx')],
                'unique_together': {('school', 'user_id', 'room_name')},
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=100)),
                ('sender_user_id', models.IntegerField()),
                ('sender_user_name', models.CharField(max_length=50)),
                ('message', models.TextField(max_length=1000)),
                ('client_message_id', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.school')),
            ],
            options={
                'indexes': [models.Index(fields=['school', 'room_name', 'created_at'], name='core_chatme_school__3579c2_idx'), models.Index(fields=['school', 'sender_user_id'], name='core_chatme_school__754484_idx')],
                'unique_together': {('school', 'room_name', 'client_message_id')},
            },
        ),
    ]
