# Generated by Django 4.2.27 on 2026-06-12 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_chatreadstate_chatmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('display_name', models.CharField(blank=True, default='', max_length=50)),
                ('nickname', models.CharField(blank=True, default='', max_length=50)),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('hobbies', models.TextField(blank=True, default='', max_length=300)),
                ('message', models.TextField(blank=True, default='', max_length=300)),
                ('avatar_key', models.CharField(blank=True, default='default', max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.school')),
            ],
            options={
                'indexes': [models.Index(fields=['school', 'user_id'], name='core_userpr_school__b3ba11_idx'), models.Index(fields=['school', 'display_name'], name='core_userpr_school__acc72a_idx')],
                'unique_together': {('school', 'user_id')},
            },
        ),
    ]
