# Generated by Django 4.2.27 on 2026-06-12 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatHiddenState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('room_name', models.CharField(max_length=100)),
                ('hidden_before_at', models.DateTimeField()),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.school')),
            ],
            options={
                'indexes': [models.Index(fields=['school', 'user_id', 'room_name'], name='core_chathi_school__0dfe64_idx')],
                'unique_together': {('school', 'user_id', 'room_name')},
            },
        ),
    ]
