# Generated by Django 4.2.27 on 2026-06-12 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_chathiddenstate'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMemo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('text', models.TextField(max_length=1000)),
                ('status', models.CharField(choices=[('planned', '予定'), ('important', '重要'), ('done', '完了')], default='planned', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.school')),
            ],
            options={
                'indexes': [models.Index(fields=['school', 'user_id', 'status', '-updated_at'], name='core_userme_school__1acfbd_idx')],
            },
        ),
    ]
