# Generated by Django 4.2.27 on 2026-06-12 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_usermemo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermemo',
            name='status',
            field=models.CharField(choices=[('none', '未分類'), ('planned', '予定'), ('important', '重要'), ('done', '完了')], default='none', max_length=20),
        ),
    ]
