# Generated by Django 4.2.27 on 2026-06-19 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_lessonstream_lessoncomment_lessonrecording'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrowthPointEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('event_type', models.CharField(choices=[('login', 'ログイン'), ('chat_person', 'チャットした相手'), ('lesson_recording_view', '授業映像の閲覧'), ('lesson_live_join', '授業ライブへの参加')], max_length=40)),
                ('event_key', models.CharField(max_length=120)),
                ('points', models.PositiveIntegerField(default=0)),
                ('season_key', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.school')),
            ],
            options={
                'indexes': [models.Index(fields=['school', 'season_key', 'event_type'], name='core_growth_school__2a2a01_idx'), models.Index(fields=['school', 'user_id', 'season_key'], name='core_growth_school__8022ea_idx')],
                'unique_together': {('school', 'user_id', 'event_type', 'event_key')},
            },
        ),
    ]
