# Generated by Codex on 2026-07-02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_backuparchive_and_password_lengths"),
    ]

    operations = [
        migrations.AddField(
            model_name="usermemo",
            name="scheduled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="usermemo",
            name="source",
            field=models.CharField(default="personal", max_length=20),
        ),
        migrations.AddIndex(
            model_name="usermemo",
            index=models.Index(fields=["school", "user_id", "scheduled_at"], name="core_userme_school__ac3d51_idx"),
        ),
    ]
