$ErrorActionPreference = "Stop"

$Root = Split-Path -Parent $PSScriptRoot
$GodotProject = Join-Path $Root "2-dmetaverse"
$ProjectGodot = Join-Path $GodotProject "project.godot"
$AppConfig = Join-Path $GodotProject "scripts\app_config.gd"
$Network = Join-Path $GodotProject "scenes\network.gd"
$LoginScene = Join-Path $GodotProject "scenes\login.tscn"
$LoginScript = Join-Path $GodotProject "scenes\login.gd"
$CommuteScene = Join-Path $GodotProject "scenes\school_commute.tscn"
$CommuteScript = Join-Path $GodotProject "scenes\school_commute.gd"
$MainScene = Join-Path $GodotProject "scenes\main.tscn"
$ChatScene = Join-Path $GodotProject "scenes\chat.tscn"
$ProfileScene = Join-Path $GodotProject "scenes\profile_panel.tscn"
$MemoScene = Join-Path $GodotProject "scenes\memo_panel.tscn"
$LessonScene = Join-Path $GodotProject "scenes\lesson_panel.tscn"
$ChatScript = Join-Path $GodotProject "scenes\chat.gd"
$ApiClient = Join-Path $GodotProject "scripts\api_client.gd"
$ProfileScript = Join-Path $GodotProject "scripts\profile_panel.gd"
$MemoScript = Join-Path $GodotProject "scripts\memo_panel.gd"
$LessonScript = Join-Path $GodotProject "scripts\lesson_panel.gd"
$PlayerScript = Join-Path $GodotProject "scripts\player.gd"
$GrowthPlantScript = Join-Path $GodotProject "scripts\growth_plant.gd"
$GrowthSummerStage0 = Join-Path $GodotProject "assets\growth\summer\stage_0.png"
$GrowthSummerStage4 = Join-Path $GodotProject "assets\growth\summer\stage_4.png"
$Skin01Idle = Join-Path $GodotProject "assets\generated\skins\skin_01\idle\1.png"
$Skin02Idle = Join-Path $GodotProject "assets\generated\skins\skin_02\idle\1.png"
$Skin01Run = Join-Path $GodotProject "assets\generated\skins\skin_01\run\1.png"
$Skin02Run = Join-Path $GodotProject "assets\generated\skins\skin_02\run\1.png"
$HudScript = Join-Path $GodotProject "scripts\hud.gd"
$WorldScript = Join-Path $GodotProject "world.gd"
$GlobalScript = Join-Path $GodotProject "global.gd"
$NakamaCompose = Join-Path $Root "nakama\docker-compose.yml"
$DjangoUrls = Join-Path $Root "team_h\core\urls.py"
$DjangoAuthViews = Join-Path $Root "team_h\core\views\auth_views.py"
$DjangoNakamaViews = Join-Path $Root "team_h\core\views\manage_api_views.py"
$DjangoConsumers = Join-Path $Root "team_h\core\consumers.py"
$DjangoModels = Join-Path $Root "team_h\core\models.py"
$ExportPresets = Join-Path $GodotProject "export_presets.cfg"
$NakamaGd = Join-Path $GodotProject "addons\com.heroiclabs.nakama\Nakama.gd"
$ExePath = Join-Path $Root "build\2Dmetaverse.exe"
$StartScript = Join-Path $PSScriptRoot "start_local_metaverse.ps1"
$ExportScript = Join-Path $PSScriptRoot "export_windows_desktop.ps1"
$TwoClientsScript = Join-Path $PSScriptRoot "start_two_local_clients.ps1"
$TailLogScript = Join-Path $PSScriptRoot "tail_godot_log.ps1"

function Assert-File($Path, $Label) {
    if (-not (Test-Path -LiteralPath $Path)) {
        throw "$Label not found: $Path"
    }
    Write-Host "OK: $Label" -ForegroundColor Green
}

function Assert-Contains($Path, $Pattern, $Label) {
    $text = Get-Content -LiteralPath $Path -Raw
    if ($text -notmatch $Pattern) {
        throw "$Label missing in $Path"
    }
    Write-Host "OK: $Label" -ForegroundColor Green
}

function Assert-NotContains($Path, $Pattern, $Label) {
    $text = Get-Content -LiteralPath $Path -Raw
    if ($text -match $Pattern) {
        throw "$Label still present in $Path"
    }
    Write-Host "OK: $Label" -ForegroundColor Green
}

Assert-File $ProjectGodot "project.godot"
Assert-File $AppConfig "AppConfig"
Assert-File $Network "Network.gd"
Assert-File $LoginScene "Login scene"
Assert-File $LoginScript "Login script"
Assert-File $CommuteScene "school commute loading scene"
Assert-File $CommuteScript "school commute loading script"
Assert-File $MainScene "Main scene"
Assert-File $ChatScene "Chat scene"
Assert-File $ProfileScene "Profile scene"
Assert-File $MemoScene "Memo scene"
Assert-File $LessonScene "Lesson scene"
Assert-File $ChatScript "Chat script"
Assert-File $ApiClient "API client"
Assert-File $ProfileScript "Profile script"
Assert-File $MemoScript "Memo script"
Assert-File $LessonScript "Lesson script"
Assert-File $PlayerScript "Player script"
Assert-File $GrowthPlantScript "Growth plant script"
Assert-File $GrowthSummerStage0 "growth summer placeholder stage 0"
Assert-File $GrowthSummerStage4 "growth summer placeholder stage 4"
Assert-File $Skin01Idle "male generated idle skin"
Assert-File $Skin02Idle "female generated idle skin"
Assert-File $Skin01Run "male generated run skin"
Assert-File $Skin02Run "female generated run skin"
Assert-File $HudScript "HUD script"
Assert-File $GlobalScript "Global script"
Assert-File $NakamaCompose "Nakama docker compose"
Assert-File $DjangoConsumers "Django websocket consumers"
Assert-File $DjangoModels "Django models"
Assert-File $ExportPresets "export_presets.cfg"
Assert-File $NakamaGd "Nakama Godot SDK"
Assert-File $StartScript "start local metaverse script"
Assert-File $ExportScript "Windows export script"
Assert-File $TwoClientsScript "start two local clients script"
Assert-File $TailLogScript "tail Godot log script"

Assert-Contains $ProjectGodot 'AppConfig="\*res://scripts/app_config\.gd"' "AppConfig autoload"
Assert-Contains $ProjectGodot 'LocalLog="\*res://scripts/local_log\.gd"' "LocalLog autoload"
Assert-Contains $ProjectGodot 'Nakama="\*res://addons/com\.heroiclabs\.nakama/Nakama\.gd"' "Nakama autoload"
Assert-Contains $ProjectGodot 'Network="\*res://scenes/network\.gd"' "Network autoload"
Assert-Contains $ProjectGodot 'run/main_scene="res://scenes/login\.tscn"' "login scene starts before metaverse"
Assert-Contains $ProjectGodot 'memo_open' "memo shortcut input action"

Assert-Contains $AppConfig 'const MODE := MODE_LOCAL' "local mode selected"
Assert-Contains $AppConfig 'const ENABLE_LOCAL_GUEST := false' "login required in local mode"
Assert-Contains $AppConfig '"custom_id": "school:%s:user:%s"' "school scoped Nakama custom id"
Assert-Contains $AppConfig '"room_name": "school-%s-lobby"' "school scoped Nakama room"
Assert-Contains $LoginScript 'DjangoApi\.login\(school_id, user_id, password\)' "Godot login submits school/user/password"
Assert-Contains $LoginScript 'res://scenes/school_commute\.tscn' "login opens commute screen before metaverse"
Assert-Contains $CommuteScript '登校中' "commute screen shows school-themed loading text"
Assert-Contains $CommuteScript 'Network\.connect_world' "commute screen starts realtime connection"
Assert-Contains $CommuteScript 'Network\.connected' "commute screen waits for realtime connection"
Assert-Contains $CommuteScript 'ProgressBar' "commute screen shows progress"
Assert-Contains $LoginScene 'RememberCheck' "login remember checkbox"
Assert-Contains $LoginScript 'SAVED_LOGIN_PATH' "login remember save path"
Assert-Contains $LoginScript '_load_saved_login' "login remember loads saved fields"
Assert-Contains $LoginScript '_update_saved_login' "login remember saves fields"
Assert-Contains $LoginScript '_show_mood_panel' "login shows student mood check"
Assert-Contains $LoginScript '_show_permission_choices' "login asks talk permission when needed"
Assert-Contains $LoginScript '_finish_login_with_mood' "login saves mood before entering metaverse"
Assert-Contains $DjangoAuthViews 'avatar_key' "Django login returns avatar skin key"
Assert-Contains $DjangoAuthViews '_default_avatar_for_gender' "Django login selects default avatar from gender"
Assert-NotContains $MainScene '\[node name="Label" type="Label" parent="HUD"\]' "debug HUD stamp label removed"
Assert-Contains $DjangoUrls 'api/login/' "Django login API URL"
Assert-Contains $DjangoUrls 'api/chat_users/' "Django chat users API URL"
Assert-Contains $DjangoUrls 'api/chat_rooms/' "Django chat rooms API URL"
Assert-Contains $DjangoUrls 'api/chat_messages/' "Django chat messages API URL"
Assert-Contains $DjangoUrls 'api/chat_read/' "Django chat read API URL"
Assert-Contains $DjangoUrls 'api/chat_clear_history/' "Django chat clear history API URL"
Assert-Contains $DjangoUrls 'api/profile/me/' "Django profile me API URL"
Assert-Contains $DjangoUrls 'api/profile/save/' "Django profile save API URL"
Assert-Contains $DjangoUrls 'api/profile/search/' "Django profile search API URL"
Assert-Contains $DjangoUrls 'api/memos/' "Django memos API URL"
Assert-Contains $DjangoUrls 'api/memos/create/' "Django memo create API URL"
Assert-Contains $DjangoUrls 'api/memos/update/' "Django memo update API URL"
Assert-Contains $DjangoUrls 'api/memos/delete/' "Django memo delete API URL"
Assert-Contains $DjangoUrls 'api/memos/teacher_targets/' "Django teacher memo targets API URL"
Assert-Contains $DjangoUrls 'api/memos/teacher_distribute/' "Django teacher memo distribute API URL"
Assert-Contains $DjangoUrls 'api/lessons/comments/' "Django lesson comments API URL"
Assert-Contains $DjangoUrls 'api/lessons/streams/' "Django lesson streams API URL"
Assert-Contains $DjangoUrls 'api/lessons/recordings/' "Django lesson recordings API URL"
Assert-Contains $DjangoUrls 'api/growth/summary/' "Django growth summary API URL"
Assert-Contains $DjangoUrls 'api/growth/event/' "Django growth event API URL"
Assert-Contains $DjangoAuthViews 'def api_login' "Django login API view"
Assert-Contains $DjangoNakamaViews 'def chat_users' "Django same-school chat users API view"
Assert-Contains $DjangoModels 'class ChatMessage' "Django persistent chat messages"
Assert-Contains $DjangoModels 'class ChatReadState' "Django chat read state"
Assert-Contains $DjangoModels 'class ChatHiddenState' "Django chat hidden state"
Assert-Contains $DjangoModels 'class UserProfile' "Django public user profile"
Assert-Contains $DjangoModels 'class UserMemo' "Django user memo"
Assert-Contains $DjangoModels 'class LessonStream' "Django lesson stream model"
Assert-Contains $DjangoModels 'class LessonComment' "Django lesson comment model"
Assert-Contains $DjangoModels 'class LessonRecording' "Django lesson recording model"
Assert-Contains $DjangoModels 'class GrowthPointEvent' "Django growth point event model"
Assert-Contains $DjangoNakamaViews 'def chat_rooms' "Django chat room unread API"
Assert-Contains $DjangoNakamaViews 'def chat_messages' "Django chat history API"
Assert-Contains $DjangoNakamaViews 'def chat_mark_read' "Django chat mark read API"
Assert-Contains $DjangoNakamaViews 'def chat_clear_history' "Django chat clear history API"
Assert-Contains $DjangoNakamaViews 'hidden_before_at' "Django chat hidden cutoff"
Assert-Contains $DjangoNakamaViews 'def profile_me' "Django profile me API view"
Assert-Contains $DjangoNakamaViews 'def profile_save' "Django profile save API view"
Assert-Contains $DjangoNakamaViews 'def profile_search' "Django profile search API view"
Assert-Contains $DjangoNakamaViews '_default_avatar_for_gender' "Django profile default avatar from gender"
Assert-Contains $DjangoNakamaViews '"gender":' "Django profile payload includes gender"
Assert-Contains $DjangoNakamaViews '"avatar_key":' "Django profile payload includes avatar key"
Assert-Contains $DjangoNakamaViews 'def memos' "Django memo list API view"
Assert-Contains $DjangoNakamaViews 'def memo_create' "Django memo create API view"
Assert-Contains $DjangoNakamaViews 'def memo_update' "Django memo update API view"
Assert-Contains $DjangoNakamaViews 'def memo_delete' "Django memo delete API view"
Assert-Contains $DjangoNakamaViews 'def teacher_memo_targets' "Django teacher memo targets API view"
Assert-Contains $DjangoNakamaViews 'def teacher_memo_distribute' "Django teacher memo distribute API view"
Assert-Contains $DjangoNakamaViews 'managed_class_ids' "Django teacher memo targets are class scoped"
Assert-Contains $DjangoNakamaViews 'def lesson_comment_post' "Django lesson comment API view"
Assert-Contains $DjangoNakamaViews 'def lesson_stream_start' "Django lesson stream start API view"
Assert-Contains $DjangoNakamaViews 'def lesson_stream_end' "Django lesson stream end API view"
Assert-Contains $DjangoNakamaViews 'stream_url = str\(data\.get\("stream_url"' "Django requires live lesson URL"
Assert-Contains $DjangoNakamaViews 'def lesson_recording_post' "Django lesson recording upload API view"
Assert-Contains $DjangoNakamaViews 'def growth_summary' "Django growth summary API view"
Assert-Contains $DjangoNakamaViews 'def growth_event' "Django growth event API view"
Assert-Contains $DjangoNakamaViews 'award_growth_points' "Django awards growth points from activity"
Assert-Contains $DjangoNakamaViews '_uploaded_lesson_video_url' "Django lesson video file upload"
Assert-Contains $DjangoNakamaViews 'lesson_videos' "Django stores uploaded lesson videos"
Assert-Contains $DjangoNakamaViews 'display_user_id = None' "Django anonymizes student comments for students"
Assert-Contains $DjangoNakamaViews 'request\.session\.get' "chat users are school scoped"
Assert-Contains $DjangoNakamaViews 'room_name = f"school-\{school_code\}-lobby"' "school based Nakama room"
Assert-Contains $ApiClient 'signal chat_users_received' "Godot chat users API signal"
Assert-Contains $ApiClient 'api/chat_users/' "Godot chat users API endpoint"
Assert-Contains $ApiClient 'fetch_chat_rooms' "Godot chat room unread fetch"
Assert-Contains $ApiClient 'fetch_chat_messages' "Godot chat history fetch"
Assert-Contains $ApiClient 'save_chat_message' "Godot chat history save"
Assert-Contains $ApiClient 'mark_chat_read' "Godot chat read marker"
Assert-Contains $ApiClient 'clear_chat_history' "Godot chat clear history"
Assert-Contains $ApiClient 'clear_all_chat_history' "Godot clear all chat history"
Assert-Contains $ApiClient 'fetch_my_profile' "Godot profile fetch"
Assert-Contains $ApiClient 'save_profile' "Godot profile save"
Assert-Contains $ApiClient 'search_profiles' "Godot profile search"
Assert-Contains $ApiClient 'current_avatar_key' "Godot API keeps current avatar key"
Assert-Contains $ApiClient 'Global\.set_avatar_key' "Godot API updates global avatar key from profile"
Assert-Contains $ProfileScript 'avatar_dirty' "profile skin choice is not overwritten by late profile fetch"
Assert-Contains $ProfileScript 'assets/generated/skins/%s/idle/1\.png' "profile preview uses generated skin image"
Assert-Contains $PlayerScript '_skin_asset_root' "player resolves generated skin asset roots"
Assert-Contains $PlayerScript '_add_texture_frames' "player loads generated skin texture frames"
Assert-Contains $PlayerScript 'assets/generated/skins/skin_02' "player can load female generated skin"
Assert-Contains $ApiClient 'fetch_memos' "Godot memo fetch"
Assert-Contains $ApiClient 'create_memo' "Godot memo create"
Assert-Contains $ApiClient 'update_memo' "Godot memo update"
Assert-Contains $ApiClient 'delete_memo' "Godot memo delete"
Assert-Contains $ApiClient 'fetch_teacher_memo_targets' "Godot fetches teacher memo targets"
Assert-Contains $ApiClient 'distribute_teacher_memo' "Godot distributes teacher memos"
Assert-Contains $ApiClient 'post_lesson_comment' "Godot lesson comment post"
Assert-Contains $ApiClient 'fetch_lesson_streams' "Godot lesson stream fetch"
Assert-Contains $ApiClient 'start_lesson_stream' "Godot lesson stream start"
Assert-Contains $ApiClient 'end_lesson_stream' "Godot lesson stream end"
Assert-Contains $ApiClient 'post_lesson_recording' "Godot lesson recording post"
Assert-Contains $ApiClient 'upload_lesson_recording_file' "Godot lesson recording file upload"
Assert-Contains $ApiClient 'fetch_growth_summary' "Godot growth summary fetch"
Assert-Contains $ApiClient 'record_growth_event' "Godot records growth events"
Assert-Contains $WorldScript 'GrowthPlantScript' "world creates growth plant"
Assert-Contains $GrowthPlantScript 'assets/growth' "growth plant uses replaceable image assets"
Assert-Contains $ApiClient '_append_multipart_text\(body, boundary, "lesson_id"' "Godot can link uploaded recording to lesson"
Assert-Contains $ApiClient 'request_raw' "Godot sends lesson upload as multipart bytes"
Assert-Contains $ApiClient 'api/logout/' "Godot logout API endpoint"
Assert-Contains $ApiClient 'auth_headers\(\)' "Godot logout sends session cookie"
Assert-Contains $ApiClient 'get_node_or_null' "Godot logout clears Global autoload"
Assert-Contains $ChatScript 'current_search_query' "chat user search state"
Assert-Contains $ChatScene 'NotoSansJP-Bold\.ttf' "bold Japanese font in chat scene"
Assert-Contains $LoginScene 'NotoSansJP-Bold\.ttf' "bold Japanese font in login scene"
Assert-Contains $ChatScript '_is_lobby_room' "global chat is hidden from chat UI"
Assert-Contains $ChatScript '_set_empty_state' "chat starts without global room"
Assert-Contains $ChatScript 'private_room_for' "private chat room selection"
Assert-Contains $ChatScript 'known_contacts' "conversation contacts are stored"
Assert-Contains $ChatScript 'unread_by_room' "chat unread count state"
Assert-Contains $ChatScript 'chat_history_cleared' "chat clears visible history after option delete"
Assert-Contains $ChatScript 'all_chat_history_cleared' "chat clears all visible histories after option delete"
Assert-Contains $ChatScript 'chat_history_limit' "chat history limit setting"
Assert-Contains $ChatScript 'chat_enter_to_send' "chat enter send setting"
Assert-Contains $ChatScript '_add_unread_divider' "unread divider label"
Assert-Contains $ChatScript '_on_chat_messages_received' "chat history render callback"
Assert-Contains $ChatScript 'if current_search_query == "":\s+return' "empty search hides non-conversation contacts"
Assert-Contains $ChatScript 'pending_contacts_by_room' "search result contacts are temporary until messaged"
Assert-Contains $ChatScript 'func open_private_chat' "profile can open private chat"
Assert-Contains $Network 'Local mode: connect authenticated user directly to Nakama' "local authenticated Nakama path"
Assert-Contains $Network 'join_chat_async' "Nakama channel join"
Assert-Contains $Network 'write_chat_message_async' "Nakama channel send"
Assert-Contains $Network 'ensure_chat_room' "Nakama dynamic chat room join"
Assert-Contains $Network 'chat_notify' "Nakama DM notification event"
Assert-Contains $Network 'school-%s-dm-%s-%s' "school scoped DM room"
Assert-Contains $Network '"event": "move"' "channel move fallback"
Assert-Contains $Network 'send_stamp' "Nakama stamp send"
Assert-Contains $Network '"event": "stamp"' "Nakama stamp channel event"
Assert-Contains $Network '"event": "state_request"' "Nakama requests lobby state after joining"
Assert-Contains $Network 'STATE_SYNC_BURST_DELAYS' "Nakama repeats initial state sync requests"
Assert-Contains $Network 'latest_player_states' "Network caches player states received during loading"
Assert-Contains $WorldScript 'cached_remote_players' "world applies cached player states after loading"
Assert-Contains $DjangoConsumers '"type": "init"' "Fallback websocket sends initial world snapshot"
Assert-Contains $DjangoConsumers 'player\.update\(data\)' "Fallback websocket preserves avatar and profile state"
Assert-Contains $Network 'disconnect_world' "Network reset on logout"
Assert-Contains $Network 'RECONNECT_DELAY' "Network has realtime reconnect delay"
Assert-Contains $Network '_schedule_reconnect' "Network schedules reconnect after realtime failure"
Assert-Contains $Network 'Realtime reconnect attempt' "Network retries realtime connection"
Assert-Contains $Network 'socket\.close\(\)' "Network closes stale Nakama socket before reconnect"
Assert-Contains $NakamaCompose 'restart:\s+unless-stopped' "Nakama services restart when Docker starts"
Assert-Contains (Join-Path $GodotProject "scripts\selection_wheel.gd") 'size = Vector2\(outer_radius \* 2\.0, outer_radius \* 2\.0\)' "visible stamp wheel size"
Assert-Contains (Join-Path $GodotProject "scripts\selection_wheel.gd") '_text_input_has_focus' "stamp wheel ignores text input"
Assert-Contains $HudScript 'func _on_chat_pressed' "HUD chat button still opens chat"
Assert-Contains $HudScript 'MemoScene' "HUD memo scene preload"
Assert-Contains $HudScript 'func _on_memo_pressed' "HUD memo button opens memo"
Assert-Contains $HudScript 'KEY_F2' "HUD memo F2 shortcut"
Assert-Contains $HudScript '_keep_memo_button_on_top' "HUD keeps memo button clickable over panels"
Assert-Contains $MemoScript 'STATUSES' "memo status list"
Assert-Contains $MemoScript 'none' "memo unclassified status"
Assert-Contains $MemoScript 'important' "memo important status"
Assert-Contains $MemoScript 'planned' "memo planned status"
Assert-Contains $MemoScript 'done' "memo done status"
Assert-Contains $MemoScript '_status_button_color' "memo status buttons use status colors"
Assert-Contains $MemoScript 'DjangoApi\.create_memo' "memo panel creates memo"
Assert-Contains $MemoScript 'DjangoApi\.update_memo' "memo panel updates memo"
Assert-Contains $MemoScript 'DjangoApi\.delete_memo' "memo panel deletes memo"
Assert-Contains $MemoScript '_autosave_input_memo' "memo panel auto-saves drafts on close"
Assert-Contains $MemoScript '_start_edit_memo' "memo panel edits existing memos"
Assert-Contains $MemoScript 'Vector2\(60, 28\)' "memo status buttons are compact"
Assert-Contains $MemoScript '_build_teacher_distribution' "memo panel has teacher distribution UI"
Assert-Contains $MemoScript '_set_memo_view' "memo panel switches self/distribution views"
Assert-Contains $MemoScript '_mode_button' "memo mode switch buttons are compact"
Assert-Contains $MemoScript '_compact_style' "memo mode switch buttons use compact padding"
Assert-Contains $MemoScript 'personal_section\.visible' "memo panel can hide self memo view"
Assert-Contains $MemoScript 'teacher_section\.visible' "memo panel can hide teacher distribution view"
Assert-Contains $MemoScript '_distribute_to_classes' "memo panel distributes to classes"
Assert-Contains $MemoScript '_distribute_to_students' "memo panel distributes to students"
Assert-Contains $HudScript 'func _on_lesson_pressed' "HUD lesson button opens lesson panel"
Assert-Contains $LessonScript 'FileDialog' "lesson panel lets teachers choose video files"
Assert-Contains $LessonScript '_start_live_stream' "lesson panel supports external live URL start"
Assert-Contains $LessonScript '_end_selected_stream' "lesson panel supports ending live lessons"
Assert-Contains $LessonScript 'streams_list' "lesson panel shows live lesson list"
Assert-Contains $LessonScript 'upload_lesson_recording_file' "lesson panel uploads selected video file"
Assert-Contains $LessonScript '_post_recording' "lesson panel supports teacher recording upload"
Assert-Contains $LessonScript '_open_url' "lesson panel supports student recording download/view"
Assert-Contains $LessonScript '_post_comment' "lesson panel student participation is comment-only"
Assert-Contains (Join-Path $GodotProject "scripts\settings_panel.gd") 'clear_chat_history' "settings can clear chat history"
Assert-Contains (Join-Path $GodotProject "scripts\settings_panel.gd") 'clear_all_chat_history' "settings can clear all chat history"
Assert-Contains (Join-Path $GodotProject "scripts\settings_panel.gd") 'clear_all_chat_history' "settings calls clear all chat history"
Assert-Contains (Join-Path $GodotProject "scripts\settings_panel.gd") 'chat_history_limit' "settings can change chat history limit"
Assert-Contains (Join-Path $GodotProject "scripts\settings_panel.gd") 'chat_enter_to_send' "settings can change enter send"
Assert-Contains $HudScript 'func _on_profile_pressed' "HUD profile button opens profile"
Assert-Contains $HudScript '_on_profile_locate_user' "profile result can locate user"
Assert-Contains $ProfileScript 'signal locate_user' "profile panel locate signal"
Assert-Contains $ProfileScript 'locate_user' "profile panel uses talk guide button"
Assert-Contains $ProfileScript 'DjangoApi\.fetch_my_profile' "profile panel fetches my profile"
Assert-Contains $ProfileScript 'DjangoApi\.search_profiles' "profile panel searches profiles"
Assert-Contains $ProfileScript '_toggle_skin_choices' "profile avatar opens skin chooser"
Assert-Contains $ProfileScript '_skin_button' "profile panel can choose avatar skin"
Assert-Contains $ProfileScript 'current_avatar_key' "profile panel saves selected avatar key"
Assert-Contains $ProfileScript '_avatar_preview_texture' "profile panel previews selected avatar skin"
Assert-Contains $GlobalScript 'allow_nearby_chat' "nearby chat setting state"
Assert-Contains $GlobalScript 'mood_status' "Global stores student mood status"
Assert-Contains $GlobalScript 'talk_permission' "Global stores talk permission"
Assert-Contains $GlobalScript 'can_be_approached_by' "Global can evaluate talk permission"
Assert-Contains $GlobalScript 'avatar_key' "Global stores avatar skin key"
Assert-Contains $GlobalScript 'default_avatar_for_gender' "Global selects default avatar by gender"
Assert-Contains $GlobalScript 'avatar_changed' "Global emits avatar change signal"
Assert-Contains $PlayerScript 'allow_nearby_chat' "player sends nearby chat setting"
Assert-Contains $PlayerScript 'talk_permission' "player sends talk permission"
Assert-Contains $PlayerScript 'mood_status' "player sends mood status"
Assert-Contains $PlayerScript 'apply_avatar_key' "player applies avatar skin key"
Assert-Contains $PlayerScript '_on_avatar_changed' "player immediately applies saved avatar changes"
Assert-Contains $PlayerScript '_frames_for_avatar' "player builds frames for selected skin"
Assert-Contains $PlayerScript 'res://assets/generated/skins/skin_02' "player supports female generated skin assets"
Assert-Contains $PlayerScript 'res://assets/generated/skins/skin_01' "player supports male generated skin assets"
Assert-Contains $PlayerScript 'show_chat_bubble' "player can show chat bubble"
Assert-Contains $HudScript 'set_nearby_talk_target' "HUD shows nearby talk button"
Assert-Contains $HudScript 'set_nearby_talk_targets' "HUD can choose nearby talk targets"
Assert-Contains $HudScript '_is_user_operating_ui' "HUD suppresses talk while any UI is active"
Assert-Contains $HudScript '_suppress_talk_prompt' "HUD hides talk prompt during UI operations"
Assert-Contains $HudScript '_build_chat_quick_button' "HUD has quick chat button"
Assert-Contains $HudScript 'unread_chat_rooms' "HUD keeps unread chat rooms"
Assert-Contains $HudScript '_on_hud_chat_rooms_received' "HUD reads unread rooms on login"
Assert-Contains $HudScript '_schedule_unread_refresh' "HUD retries unread room fetch after login"
Assert-Contains $HudScript 'mark_chat_room_read' "HUD clears badge when chat is read"
Assert-Contains $ChatScript '_can_open_private_chat' "chat checks private chat eligibility"
Assert-Contains $ChatScript '_can_send_current_room' "chat checks private message distance on send"
Assert-Contains $ChatScript 'has_player' "chat respects live talk permission when target is online"
Assert-Contains $ChatScript 'avatar_key' "chat contacts include avatar skin key"
Assert-Contains $WorldScript 'TALK_DISTANCE' "world has talk distance"
Assert-Contains $WorldScript 'can_chat_with_user' "world validates nearby chat"
Assert-Contains $WorldScript 'talk_permission' "world stores remote talk permission"
Assert-Contains $WorldScript '_can_approach_player' "world respects talk permission"
Assert-Contains $WorldScript 'avatar_key' "world syncs remote avatar key"
Assert-Contains $WorldScript 'guide_to_user' "world supports profile location guide"
Assert-Contains $WorldScript '_nearby_talkable_contacts' "world returns multiple nearby talk targets"
Assert-Contains $WorldScript 'show_chat_bubble_for_message' "world forwards chat bubbles"
Assert-Contains $HudScript 'Global\.chat_is_open = true' "chat open blocks movement"
Assert-Contains $HudScript 'Global\.chat_is_open = false' "chat close restores movement"
Assert-Contains $PlayerScript 'Global\.chat_is_open' "player ignores movement while chat is open"
Assert-Contains $HudScript 'change_scene_to_file' "logout returns to app login scene"
Assert-Contains $GlobalScript 'chat_is_open = false' "logout clears chat open state"
Assert-Contains (Join-Path $GodotProject "world.gd") 'on_player_stamp' "remote stamp display handler"
Assert-Contains $ExportPresets 'name="Windows Desktop"' "Windows Desktop export preset"
Assert-Contains $ExportPresets 'export_path="../build/2Dmetaverse.exe"' "Windows export path"

$largeTextureImports = @(
    "test\A\head\skin_A_head.png.import",
    "test\A\body\skin_A_body.png.import",
    "test\B\head\skin_B_head.png.import",
    "test\B\body\skin_B_body.png.import",
    "test\Female\Front\walk_head\skin_A_head.png.import"
)

foreach ($rel in $largeTextureImports) {
    $path = Join-Path $GodotProject $rel
    Assert-Contains $path 'process/size_limit=8192' "texture size limit $rel"
}

Write-Host "Checking Nakama realtime chat/move..." -ForegroundColor Cyan
node (Join-Path $PSScriptRoot "check_nakama_realtime_chat.js") | Out-Host
if ($LASTEXITCODE -ne 0) {
    throw "Nakama realtime chat/move check failed."
}

if (Test-Path -LiteralPath $ExePath) {
    Write-Host "OK: Windows export exists: $ExePath" -ForegroundColor Green
} else {
    Write-Warning "Windows export not found yet: $ExePath"
    Write-Warning "Export it from Godot: Project > Export > Windows Desktop"
}

Write-Host "Local setup check complete." -ForegroundColor Green
