from django.urls import path
from . import views

urlpatterns = [
    path('', views.landing, name='landing'),
    path('home', views.home, name='home'),
    path('backups/', views.backup_list, name='backup_list'),
    path('backups/create/', views.backup_create, name='backup_create'),
    path('backups/<int:archive_id>/download/', views.backup_download, name='backup_download'),
    path('backups/<int:archive_id>/restore/', views.backup_restore, name='backup_restore'),
    path('test', views.test, name='test'),
    path('godot', views.godot, name='godot'),

    path('school/register/', views.school_register, name='school_register'),
    path('school/login/', views.school_login, name='school_login'),
    path('school/logout/', views.school_logout, name='school_logout'),
    
    path('user/login/', views.user_login, name='user_login'),
    path('user/logout/', views.user_logout, name='user_logout'),
    path('user/email/', views.account_email, name='account_email'),

    path('class/create/', views.class_create, name='class_create'),
    path('class/list/', views.class_list, name='class_list'),
    path('classes/<int:class_id>/edit/', views.class_edit, name='class_edit'),
    path('classes/<int:class_id>/delete/', views.class_delete, name='class_delete'),

    path('teacher/register/', views.teacher_register, name='teacher_register'),
    path('teacher/list/', views.teacher_list, name='teacher_list'),
    path('teachers/<int:teacher_id>/edit/', views.teacher_edit, name='teacher_edit'),
    path('teachers/<int:teacher_id>/delete/', views.teacher_delete, name='teacher_delete'),

    path('student/list/', views.student_list, name='student_list'), 
    path('student/register/', views.student_register, name='student_register'),
    path('students/edit/<int:student_id>/', views.student_edit, name='student_edit'),
    path('students/delete/<int:student_id>/', views.student_delete_by_admin, name='student_delete'),
    path('teacher/students/delete/<int:student_id>/',views.student_delete_by_teacher,name='student_delete_by_teacher'),
    
    path("api/receive_form/", views.receive_form, name="receive_form"),
    path("api/get_classes/", views.get_classes, name="get_classes"),
    path("api/get_student/", views.get_student, name="get_student"),
    path("api/update_student/<int:student_id>/", views.update_student, name="update_student"),
    path("api/delete_student/<int:student_id>/",views.delete_student, name="delete_student"),
    path("api/submit_assignment/", views.submit_assignment, name="submit_assignment"),
    path("api/get_students/", views.get_students, name="get_students"),
    path("api/chat_users/", views.chat_users, name="chat_users"),
    path("api/chat_rooms/", views.chat_rooms, name="chat_rooms"),
    path("api/chat_messages/", views.chat_messages, name="chat_messages"),
    path("api/chat_messages/post/", views.chat_messages_post, name="chat_messages_post"),
    path("api/chat_read/", views.chat_mark_read, name="chat_mark_read"),
    path("api/chat_clear_history/", views.chat_clear_history, name="chat_clear_history"),
    path("api/profile/me/", views.profile_me, name="profile_me"),
    path("api/profile/save/", views.profile_save, name="profile_save"),
    path("api/profile/search/", views.profile_search, name="profile_search"),
    path("api/memos/", views.memos, name="memos"),
    path("api/memos/create/", views.memo_create, name="memo_create"),
    path("api/memos/update/", views.memo_update, name="memo_update"),
    path("api/memos/delete/", views.memo_delete, name="memo_delete"),
    path("api/memos/teacher_targets/", views.teacher_memo_targets, name="teacher_memo_targets"),
    path("api/memos/teacher_distribute/", views.teacher_memo_distribute, name="teacher_memo_distribute"),
    path("api/lessons/links/", views.lesson_recordings, name="lesson_links"),
    path("api/lessons/links/post/", views.lesson_recording_post, name="lesson_links_post"),
    path("api/growth/summary/", views.growth_summary, name="growth_summary"),
    path("api/growth/event/", views.growth_event, name="growth_event"),
    path("api/login/", views.api_login, name="api_login"),
    path("api/login/otp/", views.api_login_otp, name="api_login_otp"),
    path("api/account/email/", views.api_account_email, name="api_account_email"),
    path("api/godot_auto_login/", views.godot_auto_login),
    path("api/nakama_session/", views.nakama_session, name="nakama_session"),
    path("api/logout/", views.api_logout, name="api_logout"),

]
